<?php

namespace Grupo51\ProyectoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EncuestaLaboratorioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EncuestaLaboratorioRepository extends EntityRepository
{
	public function findAllCantLabParticipantesEncu($id_encu)
    {
       
    	$em = $this->getEntityManager();
    	$query = $em->createQuery("SELECT COUNT(e.idEncuesta) as cantidad
        		FROM Grupo51ProyectoBundle:EncuestaLaboratorio e
        		WHERE (e.idEncuesta = :id) ");
    	$query->setParameters(array('id'=>$id_encu));
		$count = $query->getSingleScalarResult();
		return $count;
    }

   
}
