<?php

namespace Grupo51\ProyectoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ResultadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultadoRepository extends EntityRepository
{

    public function findAllCantidadRespuObtenidas($id_encu){ //cantidad de respuestas obtenidas para una encuesta
    	$em = $this->getEntityManager();
    	$query = $em->createQuery("SELECT COUNT(r.idUsuario) as cantidad
        		FROM Grupo51ProyectoBundle:Resultado r
        		WHERE (r.idEncuesta = :id) ");
    	$query->setParameters(array('id'=>$id_encu));
		$count = $query->getSingleScalarResult();
		return $count;
    	
    }

     public function findByResultadosLaboratorio($id_us, $id_encu){ //obtiene el resultado de un laboratorio apra una encuesta
    	$em = $this->getEntityManager();
    	$query = $em->createQuery("SELECT r
        		FROM Grupo51ProyectoBundle:Resultado r
        		WHERE (r.idEncuesta = :ide AND r.idUsuario = :idu) ");
    	$query->setParameters(array('ide'=>$id_encu,
    								'idu'=>$id_us));
		return $query->getOneOrNullResult();
    }



}
