<?php

namespace Grupo51\ProyectoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TipoPruebaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoPruebaRepository extends EntityRepository
{
	public function findAllPruebas()
    {
       
    	$em = $this->getEntityManager();
    	$query = $em->createQuery("SELECT p 
        		FROM Grupo51ProyectoBundle:TipoPrueba p");
    	
		 return $query->getResult();
    }


}


