grupo51_proyecto_homepage:
    pattern:  /
    defaults: { _controller: Grupo51ProyectoBundle:Default:index }

grupo51_proyecto_home:
    pattern:  /home
    defaults: { _controller: Grupo51ProyectoBundle:User:home }

users:
    resource:  "@Grupo51ProyectoBundle/Controller/"	

grupo51_proyecto_estadisticas:
    pattern:  /estadisticas
    defaults: { _controller: Grupo51ProyectoBundle:Estadisticas:estadisticas }

grupo51_proyecto_obtenerEstadistica:
    pattern:  /obtenerEstadistica
    defaults: { _controller: Grupo51ProyectoBundle:Estadisticas:obtenerEstadistica }